server:
  port: 7100
app:
  id: authentication-service
apollo:
  meta: http://localhost:8080
  bootstrap:
    eagerLoad:
      enabled: true
spring:
  application:
    name: authentication-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true