server:
  port: 8000
app:
  id: roaker-common
apollo:
  meta: http://localhost:8080
  bootstrap:
    eagerLoad:
      enabled: true
spring:
  application:
    name: encrypt-platform-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true