spring:
  # Cache 配置项
  cache:
    type: REDIS
    cacheNames: roaker-cache
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  data:
    redis:
      host: localhost
      database: 1
      port: 6379
#    password: 123456 # 密码，建议生产环境开启